### ISSUE TITLE
Apex-Legends-Season-9-offsets

### ISSUE THREAD

**Issue by 04255** [stephenasuncionDEV/Apex-Legends-Season-9-Offsets#1]
Brother, how did you get the full offset of apex? Do you have a video tutorial on YouTube or anywhere else? Can you teach me how to get these offsets? thank you very much indeed

**Comment by stephenasuncionDEV** [comment]
Use the game without EAC, dump it with scylla, open the dump file with IDA, look for all reference string. However some of them I looked with reclass.
